services:
  - docker

script:
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy

  - docker tag udagram-api-feed bangnguyen/udagram-api-feed:v1
  - docker tag udagram-api-user bangnguyen/udagram-api-user:v1
  - docker tag udagram-frontend bangnguyen/udagram-frontend:v1
  - docker tag udagram-reverseproxy bangnguyen/udagram-reverseproxy:v1

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push bangnguyen/udagram-api-feed:v1
  - docker push bangnguyen/udagram-api-user:v1
  - docker push bangnguyen/udagram-frontend:v1
  - docker push bangnguyen/udagram-reverseproxy:v1