apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverseproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reverseproxy
  template:
    metadata:
      labels:
        app: reverseproxy
    spec:
      containers:
        - name: reverseproxy
          imagePullPolicy: Always
          image: bangnguyen/udagram-reverseproxy:v1
          resources:
            requests:
              cpu: "400m"
            limits:
              cpu: "500m"
          ports:
            - containerPort: 8080
      restartPolicy: Always